baseURL = 'https://example.org/'
languageCode = 'pt-BR'
title = 'UNICAP - C3'
theme = 'hugo-digital-garden-theme'
themesdir = "./themes"

Copyright = "C3 @ "

[params]
  name = "Ciência da Computação UNICAP"
  description = " é a nossa sigla de Ciência da Computaçao da católica."
  initials = "UNICAP - C3"
  googleAnalytics = ""

  [[params.social]]
    name = "Instagram"
    link = "https://www.instagram.com/c3.unicap/"
    icon = "fab fa-instagram"


[menu]
  [[menu.main]]
    name = "Professores"
    url = "/authors/"
    weight = 1
  [[menu.main]]
    name = "Eventos"
    url = "/events/"
    weight = 2
  [[menu.main]]
    name = "Projetos"
    url = "/projects/"
    weight = 3


[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = 'github'
    wrapStandAloneImageWithinParagraph = true
    [markup.goldmark.parser.attribute]
      block = false
      title = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'